builds:
  - main: ./cmd/wing
    binary: wing
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    flags: -tags netgo
  - main: ./cmd/tarmak
    binary: tarmak
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    flags: -tags netgo
    hooks:
      post: hack/minify-binaries.sh
archive:
  format: binary
release:
  github:
    owner: joshvanl
    name: tarmak
