#cloud-config
repo_update: true
repo_upgrade: all

preserve_hostname: true

users:
- default

- name: vault
  system: true
  home_dir: /var/lib/vault

write_files:
- path: /tmp/vault_server.yaml
  permissions: '0644'
  content: |
    ---
    vault_server::region: "${region}"
    vault_server::vault_tls_cert_path: "${vault_tls_cert_path}"
    vault_server::vault_tls_ca_path: "${vault_tls_ca_path}"
    vault_server::vault_tls_key_path: "${vault_tls_key_path}"
    vault_server::vault_unsealer_kms_key_id: "${vault_unsealer_kms_key_id}"
    vault_server::vault_unsealer_ssm_key_prefix: "${vault_unsealer_ssm_key_prefix}"


- path: /etc/systemd/system/puppet-init.service
  permissions: '0644'
  content: |
    [Unit]
    Description=Bootstrap vault and consul using puppet
    Wants=network-online.target
    After=network.target network-online.target

    [Service]
    Environment=AWS_REGION=${region}
    Environment=VAULT_UNSEALER_AWS_KMS_KEY_ID=${vault_unsealer_kms_key_id}
    Environment=VAULT_UNSEALER_AWS_SSM_KEY_PREFIX=${vault_unsealer_ssm_key_prefix}
    Environment=PATH=/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/bin:/opt/bin:/root/bin
    PermissionsStartOnly=true
    Restart=on-failure
    RestartSec=3
    ExecStartPre=/bin/sh -c 'set -e; mkdir -p /tmp/puppet-manifests; aws configure set s3.signature_version s3v4 && aws s3 cp "s3://${puppet_tar_gz_bucket_path}" /tmp/puppet-manifests/.; tar -xf /tmp/puppet.tar.gz -C /tmp/puppet-manifests/.; mkdir -p /tmp/puppet-manifests/modules/vault_server/hieradata; cp /tmp/vault_server.yaml /tmp/puppet-manifests/modules/vault_server/hieradata/vault_server.yaml'
    ExecStart=/bin/sh -c ' puppet apply --detailed-exitcodes --color no --environment production --modulepath /tmp/puppet-manifests/modules --hiera_config /tmp/puppet-manifests/modules/vault_server/hiera.yaml /tmp/puppet-manifests/modules/vault_server -e "include vault_server""
    [Install]
    WantedBy=multi-user.target


runcmd:
- systemctl start puppet-init.service
